- name: install yay packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - fzf
      - curl
      - bat
      - exa
      - fd
      - ripgrep
      # ripgrep-all and deps start
      - ripgrep-all
      - graphicsmagick
      - pandoc
      - poppler
      - tesseract
      # ripgrep-all deps end
      - the_silver_searcher
      # json tools start
      - jq
      - jo
      # json tools end
      - dsq
      - zoxide
      - procs
      - ncdu
      - nq-git
      - sshfs
      - tree
      - stow
      - up
      - viddy
      - shellcheck
      - duf
      - gotop
      - tldr
      - ngrok
      - croc
      - bash-bats
      - watchexec
      - python-pipx
      - tidy-viewer
      - zathura-pdf-mupdf
      - unzip
      - wget
