- name: install kubernetes packages from aur
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - kubectl
      - helm
      - flux-bin
      - rancher-k3d-bin
      - kind-bin
      - k9s
      - tilt-bin
