- name: install yay packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      # for battery, backup and stuff
      - acpi
      # X11
      - xorg-xrandr
      - xorg-xinit
      - xorg-server
      # hide mouse
      - unclutter
      # copy-paste
      - xclip
      # i3 stuff
      - i3-gaps
      - i3blocks
      - i3status
      - i3lock
      # launcher
      - rofi
      # for i3blocks
      - sysstat
      - feh
      # start xdg autostart desktop files
      - dex
      # allow regular local users to reboot etc.
      - polkit
