- hosts: "{{ variable_host | default('local') }}"
  gather_facts: true
  roles:
    - name: aur_builder-setup
      when: ansible_distribution == "Archlinux"
    - system
    # languages earliest possible (needed later)
    - python
    - go
    - rust
    #
    - tools
    - repository
    - dotfiles
    - git
    - ssh-egress
    - name: ssh-ingress
      when:
        - enable_ssh
        - ansible_system == "Linux"
    - tmux
    - neovim
    - ranger
    - shell
    - asdf
    - broot
    # macos should go through app store
    - name: tailscale
      when: ansible_system == "Linux"
    - docker
    # deprecate docker once comfortable with podman
    - podman
    # earthly requires docker
    - earthly
    - kubernetes
    - name: cloud
      when: private_machine
    - name: fonts
      when:
        - gui_apps
    - name: alacritty
      when:
        - gui_apps
    - name: window_manager
      when:
        - gui_apps
        - ansible_system == "Linux"
    - name: vscode
      when:
        - gui_apps
        - ansible_architecture == "x86_64"
    - name: vagrant
      when:
        - ansible_architecture == "x86_64"
    - name: vmware_guest
      when:
        - vmware_guest
    - name: aur_builder-cleanup
      when: ansible_distribution == "Archlinux"
    # a backup solution
    - name: restic
      when: "'devarch' in inventory_hostname"
