- name: install fonts
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - nerd-fonts-source-code-pro
      - nerd-fonts-hack
      - nerd-fonts-fira-code
      - nerd-fonts-jetbrains-mono
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
